AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for gogoro-hackthon

Resources:
  IsQuestionRelevantApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  IsQuestionRelevantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/is_question_relevant_function
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /is_question_relevant
            Method: POST
            RestApiId: !Ref IsQuestionRelevantApi
      Policies:
        - AmazonBedrockFullAccess
        - DynamoDBCrudPolicy:
            TableName: "session_table"
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:DescribeParameters
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/OPENSEARCH_ENDPOINT"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/OPENSEARCH_USERNAME"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/OPENSEARCH_PASSWORD"
        - Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: src/is_question_relevant_function
      DockerTag: python3.11-v1

Outputs:
  IsQuestionRelevantApi:
    Description: Is Question Relevant API Endpoint URL
    Value: !Sub https://${IsQuestionRelevantApi}.execute-api.${AWS::Region}.amazonaws.com/dev/is_question_relevant